// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.silent.silentmilitary.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_silent_silentmilitary_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_silent_silentmilitary_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_silent_silentmilitary_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_silent_silentmilitary_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_silent_silentmilitary_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_silent_silentmilitary_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_silent_silentmilitary_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_silent_silentmilitary_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_silent_silentmilitary_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_silent_silentmilitary_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_silent_silentmilitary_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_silent_silentmilitary_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_silent_silentmilitary_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_silent_silentmilitary_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\037com.silent.silentmilita" +
      "ry.proto\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"" +
      "\036\n\nMyResponse\022\020\n\010realname\030\002 \001(\t\"\035\n\016Stude" +
      "ntRequest\022\013\n\003age\030\001 \001(\005\":\n\017StudentRespons" +
      "e\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001" +
      "(\t\"`\n\023StudentResponseList\022I\n\017studentResp" +
      "onse\030\001 \003(\01320.com.silent.silentmilitary.p" +
      "roto.StudentResponse\"%\n\rStreamRequest\022\024\n" +
      "\014request_info\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n" +
      "\rresponse_info\030\001 \001(\t2\370\003\n\016StudentService\022" +
      "r\n\025GetRealNameByUsername\022*.com.silent.si" +
      "lentmilitary.proto.MyRequest\032+.com.silen" +
      "t.silentmilitary.proto.MyResponse\"\000\022y\n\020G" +
      "etStudentsByAge\022/.com.silent.silentmilit" +
      "ary.proto.StudentRequest\0320.com.silent.si" +
      "lentmilitary.proto.StudentResponse\"\0000\001\022\205" +
      "\001\n\030GetStudentsWrapperByAges\022/.com.silent" +
      ".silentmilitary.proto.StudentRequest\0324.c" +
      "om.silent.silentmilitary.proto.StudentRe" +
      "sponseList\"\000(\001\022o\n\006BiTalk\022..com.silent.si" +
      "lentmilitary.proto.StreamRequest\032/.com.s" +
      "ilent.silentmilitary.proto.StreamRespons" +
      "e\"\000(\0010\001B1\n\037com.silent.silentmilitary.pro" +
      "toB\014StudentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_silent_silentmilitary_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_silent_silentmilitary_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_silent_silentmilitary_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_silent_silentmilitary_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_silent_silentmilitary_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_silent_silentmilitary_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_silent_silentmilitary_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_silent_silentmilitary_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_silent_silentmilitary_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_silent_silentmilitary_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_silent_silentmilitary_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_silent_silentmilitary_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_silent_silentmilitary_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_silent_silentmilitary_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_silent_silentmilitary_proto_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_com_silent_silentmilitary_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_silent_silentmilitary_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_silent_silentmilitary_proto_StreamRequest_descriptor,
        new String[] { "RequestInfo", });
    internal_static_com_silent_silentmilitary_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_silent_silentmilitary_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_silent_silentmilitary_proto_StreamResponse_descriptor,
        new String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
